### PR TITLE
Create Python bindings

### PR DESCRIPTION
**Pull request by tridelat**
This PR is for the creation of Python bindings. Only essential classes/functions will have bindings.
So far, this concerns the following:
- [x] read_json module
- [x] core module
- [x] elasto module
- [x] aero module
- [x] servo module

Example script:
```python
import pyseahowl

# options
filepath = "../../data/IEA15MW/main.json"  # change to actual filepath
dt = 0.05
dt_output = 1.0
t_end = 200.0
t_output_next = 0.0

# get system
system_elasto = pyseahowl.elasto.SystemElastoChrono()
system_aero = pyseahowl.aero.SystemAero()
system_core = pyseahowl.core.System()
system_core.system_elasto = system_elasto
system_core.system_aero = system_aero
pyseahowl.populate_system_from_json(filepath, system_core)

# fix tower bottom nodes
for turbine in system_core.turbines:
    turbine.tower.elasto.nodes[0].set_fixed(True)
# statics
system_elasto.do_statics(True, 10)
# initialize system
system_core.initialize(system_elasto.get_time(), dt)

# simulation loop
step = 0
t_sim = 0
while t_sim < t_end:
    system_core.prestep(t_sim, dt)
    system_core.step(dt)
    step += 1
    system_core.poststep(t_sim, dt)

    t_sim = system_core.system_elasto.get_time()
    if t_sim >= t_output_next - 1e-6:
        turbine = system_core.turbines[0]
        print(
            "time: {time}, step: {step}, rpm: {rpm}, pitch: {pitch}".format(
                time=t_sim,
                step=step,
                rpm=turbine.rotor.elasto.get_rpm(),
                pitch=turbine.rotor.elasto.pitch_collective,
            )
        )
        t_output_next += dt_output

```

### CODE REVIEW

**Review by MaxPal — COMMENTED** [review]
I put an independent position code necessary on Linux.
No smoke test! 
I have a generated : pyseahowl.cpython-310-x86_64-linux-gnu.so
What do I do with that?

**Comment by MaxPal** [comment]
I also put the detection of development environment for python and add the target 
pybind11::headers. Not sure it is necessary. Perhaps directly done by pybind11_add_module macro ?

**Comment by tridelat** [comment]
> I also put the detection of development environment for python and add the target pybind11::headers. Not sure it is necessary. Perhaps directly done by pybind11_add_module macro ?

Adding pybind::headers does not seem to have an effect, so I removed it for now.

**Comment by tridelat** [comment]
Note: there is an error appearing only in Linux (Windows version is fine) when a `chrono::fea::ChNodeFEAxyzrot` is created on the C++ side: 
```*** Error in `python': double free or corruption (out): 0x00000000012cc340 ***```
Other chrono objects such as `chrono::fea::ChNodeFEAxyzD` or `chrono::ChBody` do not lead to such error. At least the simulation runs fine on the example script with that error only appearing at the end of the script (or directly after populating the turbine which calls `TurbineElasto::build` if the rest is commented out).

**Review by wenchaoyu — APPROVED** [review]
Tested on my side, works well! Great job!

**Pull request merged**
