### PR TITLE
Establish strategies for selecting models/fidelity levels

### PR DESCRIPTION
**Pull request by tridelat**
This PR is for developing a workflow for selecting different "strategies" (i.e. models, level of fidelities) for the different physical aspects (elasto, aero, etc). The main idea (to be discussed) is to develop abstract factories for each physics aspect (elasto, aero, etc), and concrete factory implementations for the selected strategy (e.g. FEM or model for elasto, in-house BEMT or AeroDyn for aero, etc). Each strategy can be or communicate with an adapter to other codes (e.g. Chrono for elasto, or AeroDyn for aero).

Taking elasto as an example, an abstract factory is used as a builder for elasto entities (nodes, elements, bodies, links). Concrete factory implementations (called "strategy" here) are then used to actually return the relevant types by calling adapters. For elasto, the concrete Chrono strategy can be used for that purpose for example.

### CODE REVIEW

**Comment by tridelat** [comment]
This PR depends on #54 being merged.

**Comment by MaxPal** [comment]
test_compnents.cpp can't compile

Not modified according to new API ! I am close to a blame ....

**Comment by tridelat** [comment]
> test_compnents.cpp can't compile
> 
> Not modified according to new API ! I am close to a blame ....

Haha, that's why it's a draft PR: not ready, the syntax is just working on seahowl_driver.
But I will push the modifications on the tests so you can be at peace ;)

**Comment by tridelat** [comment]
Closing the PR for now (outdated), will reopen a new one if we want to abstract the elasto logic.

**Pull request closed without merging**
