### PR TITLE
Couple InflowWind module into Seahowl

### LINKED ISSUE #39: Create adapter in seahowl for standalone inflowwind
to use directly the inflowind module without aerodyn
to retrieve the wind speed based on coordinates

### PR DESCRIPTION
**Pull request by wenchaoyu**
**Feature description**
This coupling can allow `seahowl` to call fortran functions from `InflowWind` module:
- can use uniform inflow wind type with different skewed angles
- can use `Turbsim` inflow wind type

**Task list to complete**
- [x] create `InflowWind` adaptor in `Seahowl`
- [x] put `const` specifier back 
- [x] clean imeplementation in `main.json` and `read_json.cpp`
- [x] update README
- [x] create test case

**Additional supporting information**
Latest main version of [aerodyn4seahowl](https://github.com/Total-RD/aerodyn4seahowl) is needed.

**Related issue, if one exists**
None

**Optional updates that might be nice someday**
None

### CODE REVIEW

**Comment by tridelat** [comment]
Updated PR for:
- Rebasing on latest `main`
- Fixing issue of `auto&` in `RotorAero` (unrelated to this PR but let's merge the fix with this PR)
- Putting `const` back in WindModel (and all derived classes)

**Review by tridelat — APPROVED** [review]
Looks good, thanks!

**Review by tridelat — CHANGES_REQUESTED** [review]
Actually, it does not compile if `SEAHOWL_ENABLE_INFLOWWIND` option is off. You should use `HAVE_INFLOWWIND` definition in read_json to only build that part if InflowWind was linked (and throw an error otherwise).

**Comment by wenchaoyu** [comment]
> Actually, it does not compile if `SEAHOWL_ENABLE_INFLOWWIND` option is off. You should use `HAVE_INFLOWWIND` definition in read_json to only build that part if InflowWind was linked (and throw an error otherwise).

It is fixed, thanks

**Review by tridelat — APPROVED** [review]
All good now, thanks!

**Pull request merged**
